version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    versioning-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"